language: php
php:
  - "7.2"
  - "7.3"
install: composer install
script: vendor/bin/phpunit tests --coverage-clover=coverage.xml --whitelist=src
after_success: bash <(curl -s https://codecov.io/bash)
